# Generated by Django 5.2.4 on 2025-11-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='reply_to_telegram_id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='chat.chatmessage'),
        ),
    ]
