# Generated by Django 5.2.4 on 2025-12-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatmessage_reply_to_telegram_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='reply_to_id',
            new_name='reply_to',
        ),
    ]
