# Generated by Django 5.2.4 on 2026-02-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_reply_to_id_chatmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited',
            field=models.DateTimeField(null=True),
        ),
    ]
