# Generated by Django 5.2.4 on 2025-07-26 14:09

import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Фамилия Имя Отчество')),
                ('phone', models.CharField(help_text='Телефон для связи')),
                ('telegram_id', models.BigIntegerField(editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Фамилия Имя Отчество')),
                ('phone', models.CharField(help_text='Телефон для связи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('CANCELLED', 'cancelled'), ('PROCESSING', 'processing'), ('COMPLETED', 'completed')], default='NEW')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('initial_requirements', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.client')),
                ('manager', models.ManyToManyField(to='orders.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(validators=[orders.models.vin_validator])),
                ('manufacture', models.CharField(help_text='Производитель')),
                ('model', models.CharField(help_text='Модель')),
                ('year', models.IntegerField(help_text='Год выпуска')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.client')),
            ],
        ),
    ]
