# Generated by Django 5.2.4 on 2025-11-16 19:03

import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Фамилия Имя Отчество')),
                ('phone', models.CharField(help_text='Телефон для связи', unique=True)),
                ('telegram_id', models.BigIntegerField(null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Фамилия Имя Отчество')),
                ('phone', models.CharField(help_text='Телефон для связи в формате +7XXXXXXXXXX')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('CANCELLED', 'Отменен'), ('PROCESSING', 'В работе'), ('COMPLETED', 'Завершен')], default='NEW')),
                ('client_status', models.CharField(choices=[('NOT_ASSIGNED', 'Новый'), ('ASSIGNED', 'Менеджер принял заказ в работу'), ('WAIT_APPROVAL', 'На согласовании с клиентом'), ('WAIT_PAYMENT', 'Ждет оплаты'), ('PAID', 'Оплачен'), ('WAIT_SEND', 'Ждет отправки у поставщиков'), ('DELIVERY', 'Отправлен'), ('READY', 'Ждет выдачи в ПВЗ'), ('FINISHED', 'Завершен')], default='NOT_ASSIGNED', null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('initial_requirements', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.client')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.manager')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_number', models.CharField(help_text='Артикул', null=True)),
                ('manufacture', models.CharField(help_text='Производитель', null=True)),
                ('name', models.CharField(help_text='Наименование', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость', max_digits=19, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_list', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(null=True, unique=True, validators=[orders.models.vin_validator])),
                ('manufacture', models.CharField(help_text='Производитель')),
                ('model', models.CharField(help_text='Модель')),
                ('year', models.IntegerField(help_text='Год выпуска')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicle_list', to='orders.client')),
            ],
        ),
    ]
