# Generated by Django 5.2.4 on 2026-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Признак, что данная позиция утверждена в заказе'),
        ),
    ]
