# Generated by Django 5.2.4 on 2025-07-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_status',
            field=models.CharField(choices=[('ASSIGNED', 'Менеджер принял заказ в работу'), ('WAIT_APPROVAL', 'На согласовании с клиентом'), ('WAIT_PAYMENT', 'Ждет оплаты'), ('PAID', 'Оплачен'), ('WAIT_SEND', 'Ждет отправки у поставщиков'), ('DELIVERY', 'Отправлен'), ('READY', 'Ждет выдачи в ПВЗ'), ('FINISHED', 'Завершен')], null=True),
        ),
    ]
