# Generated by Django 5.2.4 on 2025-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Телефон для связи', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
