# Generated by Django 5.2.4 on 2026-06-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(default=1, help_text='Количество'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_dt',
            field=models.DateTimeField(help_text='Дата поставки, заявленная поставщиком', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Скидка. 0 - 100% оплаты; 0.1 - скидка 10%', max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='internal_id',
            field=models.CharField(help_text='Внутренний идентификатор запчасти у поставщика', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='provider',
            field=models.CharField(help_text='Поставщик, например, ArmTek', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Цена у поставщица (цена закупки)', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warehouse',
            field=models.CharField(help_text='Склад поставщика', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='article_number',
            field=models.CharField(default='Артикул отсутствует', help_text='Артикул'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='manufacture',
            field=models.CharField(default='Производитель отсутствует', help_text='Производитель'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='Наименование отсутствует', help_text='Наименование'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена', max_digits=19),
        ),
    ]
