# Generated by Django 5.2.4 on 2025-07-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_client_phone_alter_client_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Телефон для связи', null=True, unique=True),
        ),
    ]
