# Generated by Django 5.2.4 on 2026-07-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_count_orderitem_delivery_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='internal_name',
            field=models.CharField(help_text='Дополнительное имя, назначается администратором', null=True),
        ),
    ]
