# Generated by Django 5.2.4 on 2026-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_client_internal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'Не задан'), ('AGREEMENT', 'На согласовании'), ('ORDERED', 'Заказан'), ('HALF_ORDERED', 'Заказан частично')], default='DEFAULT'),
        ),
    ]
