# Generated by Django 5.2.4 on 2025-08-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(help_text='Телефон для связи в формате +7XXXXXXXXXX'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('CANCELLED', 'Отменен'), ('PROCESSING', 'В работе'), ('COMPLETED', 'Завершен')], default='NEW'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_number', models.CharField(help_text='Артикул', null=True)),
                ('manufacture', models.CharField(help_text='Производитель', null=True)),
                ('name', models.CharField(help_text='Наименование', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость', max_digits=19, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
