# Generated by Django 5.2.4 on 2026-08-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='step_back',
            field=models.BooleanField(default=False, help_text='Сигнализирует, что произошло возвращение на предыдущй шаг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_status',
            field=models.CharField(choices=[('NOT_ASSIGNED', 'Новый'), ('ASSIGNED', 'Менеджер принял заказ в работу'), ('WAIT_APPROVAL', 'На согласовании с клиентом'), ('APPROVED', 'Согласован клиентом'), ('WAIT_PAYMENT', 'Ждет оплаты'), ('PAID', 'Оплачен'), ('WAIT_SEND', 'Ждет отправки у поставщиков'), ('DELIVERY', 'Отправлен'), ('READY', 'Ждет выдачи в ПВЗ'), ('FINISHED', 'Завершен')], default='NOT_ASSIGNED', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'Не задан'), ('AGREEMENT', 'На согласовании'), ('READY_FOR_ORDER', 'Готов к заказу'), ('ORDERED', 'Заказан'), ('HALF_ORDERED', 'Заказан частично')], default='DEFAULT'),
        ),
    ]
