# Generated by Django 5.2.4 on 2025-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_manager_phone_alter_order_status_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='+79999999999', help_text='Телефон для связи', unique=True),
            preserve_default=False,
        ),
    ]
