# Generated by Django 5.2.4 on 2025-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
