# Generated by Django 5.2.4 on 2026-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_step_back_alter_order_client_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'Не задан'), ('AGREEMENT', 'На согласовании'), ('APPROVED', 'Согласован клиентом'), ('REJECTED', 'Отклонён клиентом'), ('READY_FOR_ORDER', 'Готов к заказу'), ('ORDERED', 'Заказан'), ('HALF_ORDERED', 'Заказан частично')], default='DEFAULT'),
        ),
    ]
