# Generated by Django 5.2.4 on 2026-08-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='step_back',
        ),
    ]
