# Generated by Django 5.2.4 on 2025-08-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_client_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
