# Generated by Django 5.2.4 on 2026-08-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_step_back'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name', '-phone']},
        ),
        migrations.AlterField(
            model_name='order',
            name='client_status',
            field=models.CharField(choices=[('NOT_ASSIGNED', 'Новый'), ('ASSIGNED', 'В работе'), ('WAIT_APPROVAL', 'На согласовании'), ('APPROVED', 'Согласован'), ('WAIT_PAYMENT', 'Ждет оплаты'), ('PAID', 'Оплачен'), ('WAIT_SEND', 'Ждет отправки'), ('DELIVERY', 'Отправлен'), ('READY', 'Ждет выдачи в ПВЗ'), ('FINISHED', 'Завершен')], default='NOT_ASSIGNED', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'Не задан'), ('AGREEMENT', 'На согласовании'), ('APPROVED', 'Согласован клиентом'), ('REJECTED', 'Отклонён клиентом'), ('READY_FOR_ORDER', 'Готов к заказу'), ('ORDERED', 'Заказан'), ('HALF_ORDERED', 'Заказан частично'), ('READY', 'Ждет выдачи в ПВЗ')], default='DEFAULT'),
        ),
    ]
