# Generated by Django 5.2.4 on 2025-08-09 16:14

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_client_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(unique=True, validators=[orders.models.vin_validator]),
        ),
    ]
