# Generated by Django 5.2.4 on 2026-09-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_client_options_alter_order_client_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='multiplicity',
            field=models.IntegerField(default=1, help_text='Кратность'),
        ),
    ]
