# Generated by Django 5.2.4 on 2025-11-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_vehicle_client_alter_vehicle_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.client'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='manager',
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.manager'),
        ),
    ]
