# Generated by Django 5.2.4 on 2026-09-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_multiplicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_link',
            field=models.CharField(help_text='Ссылка на оплату', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_count',
            field=models.IntegerField(help_text='Общее кол-во у поставщика', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_status',
            field=models.CharField(choices=[('CANCELED', 'Отменен'), ('NOT_ASSIGNED', 'Новый'), ('ASSIGNED', 'В работе'), ('WAIT_APPROVAL', 'На согласовании'), ('APPROVED', 'Согласован'), ('WAIT_PAYMENT', 'Ждет оплаты'), ('PAID', 'Оплачен'), ('WAIT_SEND', 'Ждет отправки'), ('DELIVERY', 'Отправлен'), ('READY', 'Ждет выдачи в ПВЗ'), ('FINISHED', 'Завершен')], default='NOT_ASSIGNED', null=True),
        ),
        migrations.CreateModel(
            name='ArmTekOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_api_response', models.TextField(help_text='Ответ API при создании заказа', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armtek_order_list', to='orders.order')),
            ],
        ),
    ]
