# Generated by Django 5.2.4 on 2025-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_client_remove_order_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_status',
            field=models.CharField(choices=[('NOT_ASSIGNED', 'Новый'), ('ASSIGNED', 'Менеджер принял заказ в работу'), ('WAIT_APPROVAL', 'На согласовании с клиентом'), ('WAIT_PAYMENT', 'Ждет оплаты'), ('PAID', 'Оплачен'), ('WAIT_SEND', 'Ждет отправки у поставщиков'), ('DELIVERY', 'Отправлен'), ('READY', 'Ждет выдачи в ПВЗ'), ('FINISHED', 'Завершен')], null=True),
        ),
    ]
