# Generated by Django 5.2.4 on 2026-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderitem_confirmed_order_invoice_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armtekorder',
            name='creation_api_response',
            field=models.JSONField(help_text='Ответ API при создании заказа', null=True),
        ),
    ]
