# Generated by Django 5.2.4 on 2026-09-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_armtekorder_creation_api_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_dt',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='internal_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_time',
            field=models.IntegerField(help_text='Кол-во дней на доставку', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warehouse_code',
            field=models.CharField(help_text='Код склада', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Скидка. 0 - 100% оплаты; 0.1 - скидка 10%; 1 - бесплатно', max_digits=5),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='provider',
            field=models.CharField(choices=[('ARMTEK', 'ARMTEK')], default='ARMTEK', help_text='Поставщик, например, ArmTek', null=True),
        ),
    ]
