# Generated by Django 5.2.4 on 2026-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderitem_delivery_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Скидка. 0 - без скидки; 10 - скидка 10%; 100 - бесплатно', max_digits=5),
        ),
    ]
