# Generated by Django 5.2.4 on 2025-11-14 18:44

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_order_alter_vehicle_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(db_index=True, null=True)),
                ('reply_to_telegram_id', models.BigIntegerField(null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2025, 11, 14, 18, 44, 29, 190391, tzinfo=datetime.timezone.utc))),
                ('text', models.TextField()),
                ('media', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=10)),
                ('viewed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.client')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='orders.manager')),
            ],
        ),
    ]
