# Generated by Django 5.2.4 on 2026-09-12 13:00

from django.db import migrations


def provider_uppercase(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')
    for item in OrderItem.objects.all():
        if item.provider:
            item.provider = item.provider.upper()
            item.save(update_fields=['provider'])


def empty_operation(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_discount'),
    ]

    operations = [
        migrations.RunPython(provider_uppercase, empty_operation),
    ]
