# Generated by Django 5.2.4 on 2026-09-15 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20260912_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'Не задан'), ('AGREEMENT', 'На согласовании'), ('APPROVED', 'Согласован клиентом'), ('REJECTED', 'Отклонён клиентом'), ('ORDERED', 'Заказан'), ('HALF_ORDERED', 'Заказан частично'), ('ORDER_FAILED', 'Ошибка заказа')], default='DEFAULT'),
        ),
    ]
